#!/bin/bash

m_NS=$1
m_POD=$2

# Criação da Pastas onde serão baixados os Logs
mkdir -p /$HOME/Downloads/Logs/ >> /dev/null

# Comando do kubernets que baixa os logs
kubectl logs -n $m_NS $m_POD  >> /$HOME/Downloads/Logs/$m_POD.log

echo "Deseja Abrir o Arquivo? Y/N"
read OP

case $OP in
Y) open  /$HOME/Downloads/Logs/$m_POD.log;;
N) echo "Arquivo encontra-se no caminho:  /$HOME/Downloads/Logs/$m_POD.log" ;;
*) echo "Escolha Y ou N em caixa alta" ; ./$basename $0 ;; 
esac